"""alter tables related to self assessment

Revision ID: d7231b3e08a0
Revises: 2d1163ba8bfc
Create Date: 2024-11-26 14:03:49.245748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7231b3e08a0'
down_revision: Union[str, None] = '2d1163ba8bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('responses', sa.Column('score', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('responses', 'score', server_default=None)
    op.create_foreign_key(None, 'responses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'responses', type_='foreignkey')
    op.drop_column('responses', 'score')
    op.drop_column('responses', 'date')
    # ### end Alembic commands ###