"""Add User, Response, Question, Answer, AnswerResponse tables

Revision ID: ff8987111c5c
Revises: 8c602c4b7fd8
Create Date: 2024-11-14 13:03:50.055391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'ff8987111c5c'
down_revision: Union[str, None] = '8c602c4b7fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().dialect.has_table(op.get_bind(), 'questions'):
        op.create_table('questions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('text', sa.String(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    if not op.get_bind().dialect.has_table(op.get_bind(), 'answers'):
        op.create_table('answers',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('question_id', sa.Integer(), nullable=True),
            sa.Column('answer', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if not op.get_bind().dialect.has_table(op.get_bind(), 'responses'):
        op.create_table('responses',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if not op.get_bind().dialect.has_table(op.get_bind(), 'answer_responses'):
        op.create_table('answer_responses',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('response_id', sa.Integer(), nullable=True),
            sa.Column('answer_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
            sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_responses')
    op.drop_table('responses')
    op.drop_table('answers')
    op.drop_table('questions')
    # ### end Alembic commands ###